import Menubar from '@/components/Menubar/infex'
import './globals.css'
import { Inter } from 'next/font/google'
import { GlobalContextProvider } from '@/context/global'
import Loading from '@/components/Loading/loading'
import { TodosContextProvider } from '@/context/todosContext'
import { ModalContextProvider } from '@/context/modalsContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <GlobalContextProvider>
        <ModalContextProvider>
          <TodosContextProvider>
            <body className="bg-gray-800 relative flex flex-col items-center select-none">
              <Loading/>
              <Menubar/>
              {children}
            </body>
          </TodosContextProvider>
        </ModalContextProvider>
      </GlobalContextProvider>
    </html>
  )
}
