import Menubar from '@/components/Menubar/infex'
import './globals.css'
import { Inter } from 'next/font/google'
import { GlobalContextProvider } from '@/context/global'
import Loading from '@/components/Loading/loading'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <GlobalContextProvider>
        <body className="bg-gray-800 relative">
          <Loading/>
          <Menubar/>
          {children}
        </body>
      </GlobalContextProvider>
    </html>
  )
}
