import Menubar from '@/components/Menubar'
import './globals.css'
import { Inter } from 'next/font/google'
import { GlobalContextProvider } from '@/context/global'
import Loading from '@/components/Loading/loading'
import { TodosContextProvider } from '@/context/todosContext'
import { ModalContextProvider } from '@/context/modalsContext'
import { NotesContextProvider } from '@/context/notesContext'

export const metadata = {
  title: 'Clockboard App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <GlobalContextProvider>
        <ModalContextProvider>
          <TodosContextProvider>
            <NotesContextProvider>
              <body className="bg-gray-800 relative flex flex-col items-center select-none max-w-screen overflow-x-hidden"
              >
                <Loading/>
                <Menubar/>
                {children}
              </body>
            </NotesContextProvider>
          </TodosContextProvider>
        </ModalContextProvider>
      </GlobalContextProvider>
    </html>
  )
}
